name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: 3.x
      - run: python -m pip install black
      - run: black .
